# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e482029edfcf7c45fa84ceec881001741d72f93dc8850b016f90d9047a89d9c71c0507f26f6822b9f89e4b0e7a9a6e0ac77e43e4c4c44ab3f5a8c34b7acbf66b

test:
  secret_key_base: c9ad9a3b17fc07dae7d0bd410d14b4d15a4a3668168c878ffa4783431052e41414268cfb2ec942fcb87e0231555ed65bd175ac00763980a5eaf9bb89659592f1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
